controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

react_catch_all:
    path: /{reactRouting}
    controller: App\Controller\ReactController::index
    requirements:
        reactRouting: '.*'





